{% set version = "0.6-29" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-latticeextra
  version: {{ version|replace("-", "_") }}

source:
  fn: latticeExtra_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/latticeExtra_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/latticeExtra/latticeExtra_{{ version }}.tar.gz
  sha256: 6cadc31d56f73d926e2e8d72e43ae17ac03607a4d1a374719999a4a231e3df11

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-lattice
  run:
    - r-base
    - r-rcolorbrewer
    - r-lattice

test:
  commands:
    - $R -e "library('latticeExtra')"           # [not win]
    - "\"%R%\" -e \"library('latticeExtra')\""  # [win]

about:
  home: http://latticeextra.r-forge.r-project.org/
  license: GPL (>= 2)
  summary: Building on the infrastructure provided by the lattice package, this package provides
    several new high-level functions and methods, as well as additional utilities such
    as panel and axis annotation functions.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
